BEGIN;
DROP VIEW IF EXISTS pghero_long_running_queries;
DROP VIEW IF EXISTS pghero_running_queries;
DROP VIEW IF EXISTS pghero_missing_indexes;
DROP VIEW IF EXISTS pghero_index_usage;
DROP VIEW IF EXISTS pghero_unused_indexes;
DROP VIEW IF EXISTS pghero_relation_sizes;
DROP VIEW IF EXISTS pghero_relation_bloat;
DROP VIEW IF EXISTS pghero_relation_needs_vacuum;
DROP VIEW IF EXISTS pghero_relation_last_vacuum;
DROP VIEW IF EXISTS pghero_cache_hitrate;
DROP VIEW IF EXISTS pghero_cache_indexrate;
DROP VIEW IF EXISTS pghero_relation_hot;
DROP VIEW IF EXISTS pghero_client_statistics;
DROP FUNCTION IF EXISTS pghero_index_hit_rate();
DROP FUNCTION IF EXISTS pghero_table_hit_rate();
DROP FUNCTION IF EXISTS pghero_kill(integer);
DROP FUNCTION IF EXISTS pghero_kill_all();
COMMIT;
